### PR TITLE
Use ;; instead of ; for line comments

### PR DESCRIPTION
**Pull request by plexus**
LISPs in general and Clojure in particular by convention uses double semicolons
for regular line comments. Single semicolons are reserved for trailing comments
at the end of a line, and are treated (aligned) differently in some editors,
notably Emacs.

### CODE REVIEW

**Comment by plexus** [comment]
This is something a lot of Calva users are complaining about, blaming Calva even though it's really an upstream issue: https://github.com/BetterThanTomorrow/calva/issues/971

**Comment by alexr00** [comment]
Thanks for the PR! Can you point me to some language documentation so I can learn more?

**Comment by plexus** [comment]
See for example the community style guide: https://github.com/bbatsov/clojure-style-guide#comments

**Review by alexr00 — APPROVED** [review]

**Comment by plexus** [comment]
Thanks for the quick merge!

**Comment by ArturoDent** [comment]
@plexus - purely as a very short-term workaround until the next release in a couple of weeks, you can change lineComment form with this extension:  [Custom Language Properties](https://marketplace.visualstudio.com/items?itemName=ArturoDent.custom-language-syntax).

    "custom-language-properties": {
      "clojure.comments.lineComment": ";;"
     },

**Pull request merged**
